import adapterCloudflare from '@sveltejs/adapter-cloudflare';
import adapterNode from '@sveltejs/adapter-node';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';

// Two build targets, one config:
// - default (`npm run build`): adapter-cloudflare -> .svelte-kit/cloudflare,
//   which is what the Cloudflare Pages dashboard build command expects.
// - `SVELTE_ADAPTER=node` (`npm run build:node`, also set by the frontend
//   Dockerfile): adapter-node -> build/index.js so the self-hosted production
//   server (`node build/index.js`) is actually regenerated by a build.
// Without the node target, `npm run build` leaves build/ untouched and
// `node build/index.js` keeps serving whatever artifact is already there.
const adapter = process.env.SVELTE_ADAPTER === 'node' ? adapterNode() : adapterCloudflare();

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://svelte.dev/docs/kit/integrations
	// for more information about preprocessors
	preprocess: vitePreprocess(),
	kit: {
		adapter
	}
};

export default config;
